# Generated by Django 5.0.3 on 2024-03-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(default="default my descripttion"),
            preserve_default=False,
        ),
    ]
