# Generated by Django 5.0.3 on 2024-03-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_book_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="qualification",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
