# Generated by Django 5.0.3 on 2024-03-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_book_qualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
